Repository apel/apel, pull requests merged in 2024-05, with the labels that each got.

#351 Apel FPM build script
  CHANGELOG
  scripts/apel-build.sh
  scripts/apel-server-helper.sh
Labels: enhancement, dependencies

#224 Remove support for Oracle as a backend database
  apel/db/apeldb.py
  apel/db/backends/oracle.py
Labels: enhancement

#366 Code quality
  apel/db/loader/loader.py
  apel/db/unloader.py
  bin/parser.py
  bin/retrieve_dns.py
  bin/summariser.py
  scripts/migrate_apel.py
  test/test_aur_parser.py
  test/test_blah.py
  test/test_car_parser.py
  test/test_hashing.py
  test/test_htcondor_parser.py
  test/test_logging.py
  test/test_lsf.py
  test/test_pbs.py
  test/test_record_factory.py
  test/test_slurm.py
  test/test_star_parser.py
Labels: bug, enhancement

#367 Remove redundant Python 3 test from Travis and add caching to GH Action
  .github/workflows/unit-test.yml
  .travis.yml
Labels: enhancement, github_actions

#369 change `try...finally` to `with...` when used for `open`
  test/test_retrieve_dns.py
Labels: enhancement

#368 Setup.py to build and install the package underneath
  setup.py
Labels: bug
